### ISSUE TITLE
Doesn't work on macOS Monterey 12.0.1 (M1)

### ISSUE THREAD

**Issue by Marfa** [a1usha/HideMyDock#1]
I receive [this error](https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac) when I try to launch your app.

<a href="https://ibb.co/gt5BNR1"><img src="https://i.ibb.co/gt5BNR1/2qqwqw.png" alt="2qqwqw" border="0"></a>

I know about workaround, but anyway.

**Comment by a1usha** [comment]
As far as I know, to fix this problem, the developer must have a special dev account in order to be able to sign his software for further distribution. According to Apple documentation, such an account costs $99 per year. I’m not ready to give up that kind of money to distribute such a small application.

Therefore, I apologize for such a message, you can only believe me in a word that there is no malicious code there.

If you know of any way to sign applications without a certified account, I will be glad to know about it.

**Comment by emirhangunec** [comment]
You can bypass the error with these steps:
1. Open the Applications Folder and Find the HideMyDock
2. Right-click to HideMyDock and click Open
3. Select open in the popup
4. Then, you can start the app as you wish!
